parameters:
  - name: pipelineJobs
    type: object

jobs:
  - ${{ each pipelineJob in parameters.pipelineJobs }}:
    - job: "${{pipelineJob.name}}"
      pool:
        name: 'Azure Pipelines'
        vmImage: 'windows-latest'
      steps:
        - template: steps.yml
          parameters:
            browser: ${{pipelineJob.browser}}
            fromjob: ${{pipelineJob.name}}