schedules:
  - cron: "0 0 * * *"
    displayName: Daily Regression Run
    branches:
      include:
        - master

jobs:
  - template: multijob.yml
    parameters:
      pipelineJobs:
        - { name: 'Regression for Chrome', browser: 'chrome' }
        - { name: 'Regression for Firefox', browser: 'firefox' }
        - { name: 'Regression for Edge', browser: 'edge' }