schedules:
  - cron: "0 0 * * *"
    displayName: Daily Regression Run
    branches:
      include:
        - master

jobs:
  - template: ./templates/multijob.yml
    parameters:
      pipelineJobs:
        - { name: 'Regression_Chrome', browser: 'chrome' }
        - { name: 'Regression_Firefox', browser: 'firefox' }
        - { name: 'Regression_Edge', browser: 'edge' }